### ISSUE TITLE
Made Intellij idea 15.04 ebuild

### ISSUE THREAD

**Issue by fufik** [mrueg/mrueg-overlay#11]
Made IntelliJ Idea 15.0.4.143.2287.1 ebuild based on your 15.0.0.143.381.42 ebuild.
I installed it and it seems that it works fine. How can I add it in your overlay?

**Comment by mrueg** [comment]
I'll add the 2016.x releases soonish.

**Comment by fufik** [comment]
already have it, check my overlay

**Comment by mrueg** [comment]
Please use the version that is available in upstream repository.
