### ISSUE TITLE
x11-plugins/purple-hangouts: requires >=net-im/pidgin-2.10.12

### ISSUE THREAD

**Issue by fdutheil** [mrueg/mrueg-overlay#13]
Hi,

I've tested this ebuild, and it works, provided I unmask net-im/pidgin-2.10.12-r2.
With net-im/pidgin-2.10.11(actual stable version) libpurple returns (via finch --debug):
```
plugins: /usr/lib64/purple-2/libhangouts.so is not loadable: undefined symbol: purple_media_set_send_rtcp_mux
```

Thanks for this ebuild, I'm using it with bitlbee.

**Comment by mrueg** [comment]
Thanks! Fixed in 25cd99eb88a7e9ff5061e434d6eca1c6a6225899
